name: CI

on:
  push:
    branches:
      - main

jobs:
  # PHP 8.4 Debian
  build-8_4-cli:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.4-cli
    secrets: inherit
    with:
      source-directory: 8.4/cli
      image-tag: fuadkleb/php-mssql:8.4-cli

  build-8_4-fpm:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.4-fpm
    secrets: inherit
    with:
      source-directory: 8.4/fpm
      image-tag: fuadkleb/php-mssql:8.4-fpm

  build-8_4-franken:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.4-franken
    secrets: inherit
    with:
      source-directory: 8.4/franken
      image-tag: fuadkleb/php-mssql:8.4-franken

  # PHP 8.3 Debian
  build-8_3-cli:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.3-cli
    secrets: inherit
    with:
      source-directory: 8.3/cli
      image-tag: fuadkleb/php-mssql:8.3-cli

  build-8_3-fpm:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.3-fpm
    secrets: inherit
    with:
      source-directory: 8.3/fpm
      image-tag: fuadkleb/php-mssql:8.3-fpm

  # PHP 8.2 Debian
  build-8_2-cli:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.2-cli
    secrets: inherit
    with:
      source-directory: 8.2/cli
      image-tag: fuadkleb/php-mssql:8.2-cli

  build-8_2-fpm:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.2-fpm
    secrets: inherit
    with:
      source-directory: 8.2/fpm
      image-tag: fuadkleb/php-mssql:8.2-fpm

  # PHP 8.1 Debian
  build-8_1-cli:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.1-cli
    secrets: inherit
    with:
      source-directory: 8.1/cli
      image-tag: fuadkleb/php-mssql:8.1-cli

  build-8_1-fpm:
    uses: ./.github/workflows/createtest.yml
    name: fuadkleb/php-mssql:8.1-fpm
    secrets: inherit
    with:
      source-directory: 8.1/fpm
      image-tag: fuadkleb/php-mssql:8.1-fpm
